# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapShot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapShot

  target 'SnapShotTests' do
    inherit! :search_paths
    pod 'iOSSnapshotTestCase'
  end

  target 'SnapShotUITests' do
    # Pods for testing
  end

end
